export const theme = {
  colors: {
    bg: '#ffffff',
    surface: '#ffffff',
    canvas: '#f7f8f8',
    fg: '#1e2733',
    muted: '#4b535f',
    border: '#dde6ed',
    accent: '#94c2f3',
    accentDeep: '#004e93',
    accentSoft: '#d7eaff',
    accentTint: '#edf6ff',
    fgSoft: '#f1f4f7',
    statusGoodTint: '#d2f6dd',
    statusGoodDeep: '#005226',
    statusWarnTint: '#feedc9',
    statusWarnDeep: '#6d4400',
    statusBadTint: '#ffe0dc',
    statusBadDeep: '#861118',
  },
  typography: {
    fontBody: 'System',
    fontDisplay: 'System',
    fontMono: 'monospace',
  },
  radii: {
    sm: 14,
    md: 20,
    lg: 28,
    pill: 999,
  },
  spacing: {
    gutter: 22,
    card: 24,
    navInset: 16,
  },
  shadows: {
    sm: {
      shadowColor: '#1e2733',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.07,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: '#1e2733',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 28,
      elevation: 5,
    },
    lg: {
      shadowColor: '#1e2733',
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.14,
      shadowRadius: 32,
      elevation: 8,
    },
  },
};
